#
# The YAML file is a lightweight markup language file that supports all
# ROS parameter types. It's used by rosparam to load static parameters to
# the Parameter Server, which are commonly used to initialize part of a
# system and rarely change on run-time. Sometimes the user modifies this
# file before starting a node. This file is usually in the /config subdirectory
# of a package. Note that when dynamic reconfiguration is implemented for
# a package, most parameters will be dynamic, making this file barely used.
#
#                    _________ NOTES _________
#
# If the stimulation channels 1,2,3,4 are used in a matrix with the desired
# frequency of 12Hz for each channel, then the overall stimulation frequency
# will be 12x4 = 48Hz.
#

channels: [1,2,3,4] # List of active channels in the matrix
freq: 48 # Overall stimulation frequency in Hz 
